spring.data.mongodb.uri=${MONGO_URL:mongodb://localhost:27017/dev}

spring.freemarker.suffix=.ftl
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

minio.host=${MINIO_HOST:localhost}
minio.bucket=${MINIO_BUCKET:image-storage}
minio.access.key=${MINIO_ACCESS_KEY:}
minio.secret.key=${MINIO_SECRET_KEY:}
minio.useSSL=${MINIO_USE_SSL:false}
minio.reconnect.enabled=${MINIO_RECONNECT_ENABLED:true}